version: "3.9"

services:
  db:
    image: postgres:15
    container_name: telegraph_db_container
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password_123"
      POSTGRES_DB: "telegraph_db"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  posts_service:
    build: 
      context: ./posts_service
      dockerfile: Dockerfile
    container_name: posts_service_container
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password_123"
      POSTGRES_DB: "telegraph_db"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
    depends_on:
      - db
    ports:
      - "8001:8001"

  comments_service:
    build:
      context: ./comments_service
      dockerfile: Dockerfile
    container_name: comments_service_container
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password_123"
      POSTGRES_DB: "telegraph_db"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      SENTIMENT_HOST: "sentiment_service"
      SENTIMENT_PORT: "8003"
    depends_on:
      - db
      - sentiment_service
    ports:
      - "8002:8002"

  sentiment_service:
    build:
      context: ./sentiment_service
      dockerfile: Dockerfile
    container_name: sentiment_service_container
    environment:
      MODEL_NAME: "cointegrated/rubert-tiny2-cedr-emotion-balanced"
      ONNX_MODEL_PATH: "/app/model.onnx"
    ports:
      - "8003:8003"
    depends_on:
      - db

volumes:
  db_data:
